# Generated by Django 6.0.5 on 2026-05-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_fee_order_tip_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
