# Generated by Django 6.0.6 on 2026-06-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_customer_feedback_order_customer_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('issue_type', models.CharField(choices=[('Order Issue', 'Order Issue'), ('Delivery Issue', 'Delivery Issue'), ('Payment Issue', 'Payment Issue'), ('Product Quality Issue', 'Product Quality Issue'), ('Cancel Order', 'Cancel Order'), ('Other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
